--Creacion Base de datos
CREATE DATABASE [ECOMMERCE_DB]
GO

--Indicamos que usaremos esta base de datos para la creacion de las tablas

USE [ECOMMERCE_DB]
GO

CREATE TABLE CUSTOMER(
		CUSTOMER_ID INT IDENTITY(1,1) PRIMARY KEY,
		NOMBRE VARCHAR(50) NOT NULL,
		APELLIDO VARCHAR(50) NOT NULL,
		EMAIL VARCHAR(50) NOT NULL UNIQUE, --no seria necesario (no esta en el alcance del enunciado que el mail sea unico)
		SEXO VARCHAR(10),
		DIRECCION VARCHAR(50) NOT NULL,
		FECHA_NACIMIENTO DATE NOT NULL,
		TELEFONO VARCHAR(250) NOT NULL
);


CREATE TABLE CATEGORY(
		CATEGORY_ID INT IDENTITY(1,1) PRIMARY KEY,
		NOMBRE VARCHAR(50) NOT NULL,
		DESCRIPCION VARCHAR(500),
		PATH VARCHAR(100)
);


CREATE TABLE ITEM(
		ITEM_ID INT IDENTITY(1,1) PRIMARY KEY,
		NOMBRE VARCHAR(50) NOT NULL,
		DESCRIPCION VARCHAR(500),
		PRECIO DECIMAL(10,2) NOT NULL,
		ESTADO VARCHAR(10) NOT NULL,
		FECHA_BAJA DATE,
		CATEGORY_ID INT,
		CONSTRAINT CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);



CREATE TABLE [ORDER](
		ORDER_ID INT IDENTITY(1,1) PRIMARY KEY,
		FECHA_ORDER DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		BUYER_ID INT NOT NULL,
		SELLER_ID INT NOT NULL,
		ITEM_ID INT NOT NULL,
		CANTIDAD INT NOT NULL CHECK (CANTIDAD > 0), --no se pueden comprar 0 unidades
		PRECIO_VENTA DECIMAL(10,2) NOT NULL, --precio del item al momento de la venta
		PRECIO_TOTAL DECIMAL (10,2) NOT NULL,
		CONSTRAINT FK_ORDER_BUYER FOREIGN KEY (BUYER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
		CONSTRAINT FK_ORDER_SELLER FOREIGN KEY (SELLER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
		CONSTRAINT FK_ORDER_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
);

CREATE TABLE ITEM_HISTORY (
    ITEM_HISTORY_ID INT IDENTITY(1,1) PRIMARY KEY,
    ITEM_ID INT NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    ESTADO VARCHAR(10) NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ITEM_HISTORY_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
);

